### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by thu4nvd** [thu4nvd/nodejs-basic-bnmd#1]
### Current Behavior:

Error show when run `npm start`

	    SyntaxError: Invalid or unexpected token
	    	at wrapSafe (internal/modules/cjs/loader.js:988:16)
	    	at Module._compile (internal/modules/cjs/loader.js:1036:27)
	    	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
	    	at Module.load (internal/modules/cjs/loader.js:937:32)
	    	at Function.Module._load (internal/modules/cjs/loader.js:778:12)
	    	at Module.require (internal/modules/cjs/loader.js:961:19)
	    	at require (internal/modules/cjs/helpers.js:92:18)
	    	at Object.<anonymous> (D:\workspace\nodejs-basic-bnmd\node_modules\core-js\stable\index.js:158:1)
	    	at Module._compile (internal/modules/cjs/loader.js:1072:14)
	    	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
	    [nodemon] app crashed - waiting for file changes before starting...

### Expected Behavior:

    [nodemon] starting `babel-node src/server.js`
    Example app listening at http://localhost:8080

### Steps To Reproduce:

1. In this environment: below
2. With this config...

    npm install --save-exact express@4.17.1
    npm install --save-exact ejs@3.1.6
    npm install --save-exact body-parser@1.19.0
    npm install --save-exact nodemon@2.0.12
    npm install --save-exact @babel/core@7.15.5
    npm install --save-exact @babel/node@7.15.4 @babel/preset-env@7.15.6
    npm install --save-exact dotenv@10.0.0

3. Run 'npm start'

### Environment:

- OS: Windows 10 Pro . ver: 
- Node: v14.17.6
- npm: 6.14.15

**Comment by thu4nvd** [comment]
## Observation

File es.regexp.exec.js turns to binary

## Workaround

Find the text content in the repo then edit the file
	D:\workspace\nodejs-basic-bnmd\node_modules\core-js\modules
	https://github.com/zloirock/core-js
